version: 0.2

env:
  parameter-store:
    GITHUB_USER: "/github.com/finatext/cicd-user"
    GITHUB_TOKEN: "/github.com/finatext/cicd-token"

phases:
  pre_build:
    commands:
      - if [ "$(git branch --contains $(git rev-parse HEAD) | sed -e 's|[\* ]*||' | grep -E ^${APPROVED_BRANCH_NAME}$)" = "" ]; then echo Not a permitted branch...; exit 1; fi
      - docker login ghcr.io -u "${GITHUB_USER}" -p "${GITHUB_TOKEN}"
      - TOKEN="${GITHUB_TOKEN}"
      - echo -e "\n//npm.pkg.github.com/:_authToken=$TOKEN" >> .npmrc
      - |
        docker run --rm -v $(pwd):/work -w /work \
          ghcr.io/finatext/docker-images/node:12.13.1 \
          yarn install
  build:
    commands:
      - |
        docker run --rm -v $(pwd):/work -w /work \
          ghcr.io/finatext/docker-images/node:12.13.1 \
          yarn build:${BUILD_ENV}
artifacts:
  files:
    - '**/*'
